### PR TITLE
Display error when failing to set wallpaper on linux

### PR DESCRIPTION
**Pull request by joajfreitas**

### CODE REVIEW

**Comment by davidpob99** [comment]
Hi, thank you for contributing, I think this change is necessary in order to debug failures.

However, there are two warnings that should be fixed before merging the changes

```
warning: trait objects without an explicit `dyn` are deprecated
  --> src/main.rs:56:54
   |
56 | type WallpaperResult<T> = std::result::Result<T, Box<Error>>;
   |                                                      ^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2018) but is a hard error in Rust 2021!
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
   = note: `#[warn(bare_trait_objects)]` on by default
help: use `dyn`
   |
56 | type WallpaperResult<T> = std::result::Result<T, Box<dyn Error>>;
   |                                                      +++

warning: use of deprecated method `std::error::Error::description`: use the Display impl or to_string()
   --> src/main.rs:380:65
    |
380 |                         println!("{}", format!("Error: {}", err.description()).red());
    |                                                                 ^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

**Review by davidpob99 — CHANGES_REQUESTED** [review]
Hi, thank you for contributing, I think this change is necessary in order to debug failures.

However, there are two warnings that should be fixed before merging the changes

```
warning: trait objects without an explicit `dyn` are deprecated
  --> src/main.rs:56:54
   |
56 | type WallpaperResult<T> = std::result::Result<T, Box<Error>>;
   |                                                      ^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2018) but is a hard error in Rust 2021!
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
   = note: `#[warn(bare_trait_objects)]` on by default
help: use `dyn`
   |
56 | type WallpaperResult<T> = std::result::Result<T, Box<dyn Error>>;
   |                                                      +++

warning: use of deprecated method `std::error::Error::description`: use the Display impl or to_string()
   --> src/main.rs:380:65
    |
380 |                         println!("{}", format!("Error: {}", err.description()).red());
    |                                                                 ^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

**Comment by joajfreitas** [comment]
Fixed the build warnings and took the opportunity to also fix some clippy warnings

**Review by davidpob99 — APPROVED** [review]

**Comment by joajfreitas** [comment]
There were some conflicts, hope it's good now

**Comment by davidpob99** [comment]
I was also fixing them. Thanks

**Pull request merged**
